# ./docker-compose.yml

version: '3.7'

services:
  db:
    image: mysql:latest
    volumes:
    - mysql-data:/var/lib/mysql
  
  web:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - "8100:80"

volumes:
    mysql-data:
